static void SysInit(){
	//I/O Init
	#define SLED(x)		_SET(SLED_PORT,SLED_Bit,x)
	_SET(SLED_DDR,SLED_Bit,1);
	#define BCKLT(x)	_SET(LCDLED_PORT,LCDLED_Bit,!x)
	_SET(LCDLED_DDR,LCDLED_Bit,1);
	_SET(BTNX1_DDR,BTNX1_Bit,1);_SET(BTNX1_PORT,BTNX1_Bit,0);
	_SET(BTNX2_DDR,BTNX2_Bit,1);_SET(BTNX2_PORT,BTNX2_Bit,0);
	_SET(BTNY1_DDR,BTNY1_Bit,0);_SET(BTNY1_PORT,BTNY1_Bit,1);
	_SET(BTNY2_DDR,BTNY2_Bit,0);_SET(BTNY2_PORT,BTNY2_Bit,1);
	_SET(BTNY3_DDR,BTNY3_Bit,0);_SET(BTNY3_PORT,BTNY3_Bit,1);
	#define BTNCOM(x) _SET(BTNX1_PORT,BTNX1_Bit,x);_SET(BTNX1_DDR,BTNX1_Bit,!x);_SET(BTNX2_PORT,BTNX2_Bit,!x);_SET(BTNX2_DDR,BTNX2_Bit,x)
	#define BTN3	!_READ(BTNY1_PIN,BTNY1_Bit)
	#define BTN2	!_READ(BTNY2_PIN,BTNY2_Bit)
	#define BTN1	!_READ(BTNY3_PIN,BTNY3_Bit)
	#define BTN4	!_READ(BTNY1_PIN,BTNY1_Bit)
	#define BTN5	!_READ(BTNY2_PIN,BTNY2_Bit)
	#define BTN6	!_READ(BTNY3_PIN,BTNY3_Bit)
	#define IO1(x)	_SET(IO1_PORT,IO1_Bit,x)
	_SET(IO1_DDR,IO1_Bit,1);
	#define IO2(x)	_SET(IO2_PORT,IO2_Bit,x)
	_SET(IO2_DDR,IO2_Bit,1);
	#define IO3(x)	_SET(IO3_PORT,IO3_Bit,x)
	_SET(IO3_DDR,IO3_Bit,1);
	
}